            Running setup.py install for gunicorn
               Traceback (most recent call last):
                 File "<string>", line 1, in <module>
               ImportError: No module named setuptools
               Complete output from command /app/.heroku/python/bin/python -c "import setuptools;__file__='/tmp/pip-build-u46314/gunicorn/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-UCdZuN-record/install-record.txt --single-version-externally-managed:
               Traceback (most recent call last):

             File "<string>", line 1, in <module>

           ImportError: No module named setuptools

           ----------------------------------------
           Command /app/.heroku/python/bin/python -c "import setuptools;__file__='/tmp/pip-build-u46314/gunicorn/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-UCdZuN-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip-build-u46314/gunicorn
           Storing complete log in /app/.pip/pip.log

     !     Push rejected, failed to compile Python app

    To git@heroku.com:nameless-mesa-2099.git
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'git@heroku.com:nameless-mesa-2099.git'
